import { createApp } from "vue";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./style.css";
import App from "./App.vue";
import router from "./router";
import VueToast from "vue-toast-notification";
import "vue-toast-notification/dist/theme-bootstrap.css";
const app = createApp(App);
app.use(VueToast);
app.use(router);
app.mount("#app");
